---
title: "Data Manipulation with tidyr"
output:
  html_document:
    highlight: pygments
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: 3
fontsize: 12 pt
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE) #to supress warning messages in all output
```

***

#Importing the Acitelli dataset into R.

```{r}
acitelli_ind <- read.csv(file.choose(), header=TRUE)
```

We ultimately want to get our data into the pairwise format for the APIM. We'll need some more packages.

```{r}
#install.packages("tidyr")
#install.packages("dplyr")

library(tidyr)
library(dplyr)
```



##Individual to Dyad Structure

```{r}
acitelli_dyd <- acitelli_ind %>% 
  mutate(gender = ifelse(gender == 1, "H", "W")) %>%
  gather(variable, value, self_pos:simhob) %>%
  unite(var_gender, variable, gender) %>%
  spread(var_gender, value)

head(acitelli_dyd)
```


##Individual to Pairwise Structure

```{r}
tempA <- acitelli_ind %>% 
  mutate(genderE = gender, partnum = 1) %>%
  mutate(gender = ifelse(gender == 1, "A", "P")) %>%
  gather(variable, value, self_pos:genderE) %>%
  unite(var_gender, variable, gender) %>%
  spread(var_gender, value)

tempB <- acitelli_ind %>% 
  mutate(genderE = gender, partnum = 2) %>%
  mutate(gender = ifelse(gender == 1, "P", "A")) %>%
  gather(variable, value, self_pos:genderE)%>%
  unite(var_gender, variable, gender) %>%
  spread(var_gender, value)

acitelli_pair <- bind_rows(tempA, tempB) %>%
  arrange(cuplid) 
  
rm(tempA, tempB)
head(acitelli_pair)
```

***

#[Dave's Kenny's restructuring apps](http://davidakenny.net/RDDD.htm)

***
